name: toilet_duck
description: A new Flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  get: ^4.6.1
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/pages/
    - assets/images/pages/splash/
    - assets/images/pages/p0/introduction/
    - assets/images/pages/p0/sign_in/
    - assets/images/pages/p0/sign_up/
    - assets/images/pages/p1/home/side_menu/notification.png
    - assets/images/pages/p1/home/side_menu/user.png
    - assets/images/pages/p1/home/side_menu/setting.png
    - assets/images/pages/p1/home/side_menu/close_duck.png
    - assets/images/pages/p1/home/side_menu/big_duck.png

  fonts:
    - family: KurewaGothic
      fonts:
        - asset: assets/fonts/KurewaGothicCjkJp-SemiBold-2.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
